const userActionTypes = {
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

  BAN_USER_REQUEST: 'BAN_USER_REQUEST',
  BAN_USER_SUCCESS: 'BAN_USER_SUCCESS',
  BAN_USER_FAILURE: 'BAN_USER_FAILURE',

  UNBAN_USER_REQUEST: 'UNBAN_USER_REQUEST',
  UNBAN_USER_SUCCESS: 'UNBAN_USER_SUCCESS',
  UNBAN_USER_FAILURE: 'UNBAN_USER_FAILURE',

  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE'
};

export default userActionTypes;